DROP TABLE IF EXISTS Type;

CREATE TABLE IF NOT EXISTS Type ( 
    name VARCHAR (19)  NOT NULL PRIMARY KEY,
    category VARCHAR (17) NOT NULL,
    FOREIGN KEY (category) REFERENCES Category (category)  
);

INSERT INTO Type (category, name) VALUES 
    ("Whirlwind Master", "Spear"),
    ("Whirlwind Master", "Pike"),
    ("Whirlwind Master", "Double Voulge"),
    ("Whirlwind Master", "Great Sword"),
    ("Whirlwind Master", "Club"),
    ("Whirlwind Master", "Gloves"),
    ("Whirlwind Master", "Halberd"),
    ("Whirlwind Master", "Twin Axes"),
    ("Whirlwind Master", "Lance"),
    ("Whirlwind Master", "Twin Rods"),
    ("Whirlwind Master", "Axe"),
    ("Whirlwind Master", "Tonfa"),
    ("Whirlwind Master", "Crossbow"),
    ("Whirlwind Master", "Arm Cannon"),
    ("Whirlwind Master", "Brush"),
    ("Whirlwind Master", "Dagger Axe"),
    ("Whirlwind Master", "Bomb"),
    ("Whirlwind Master", "Short Pike"),
    ("Whirlwind Master", "Great Axes"),
    ("Whirlwind Master", "Mace"),
    ("Whirlwind Master", "Spiked Shield"),
    ("Whirlwind Master", "Arm Blade"),
    ("Whirlwind Master", "Circle Blade"),
    ("Whirlwind Master", "Siege Spear"),
    ("Whirlwind Master", "Bow & Rod"),
    ("Whirlwind Master", "Wheeled Halberd"),
    ("Whirlwind Master", "Rake"),
    ("Whirlwind Master", "Dual-Headed Mace"),
    ("Whirlwind Master", "Revolving Crossbow"),
    ("Whirlwind Master", "War Trident"),
    ("Whirlwind Master", "Sele"),
    
    ("Dasher", "Sword"),
    ("Dasher", "Rapier"),
    ("Dasher", "War Fan"),
    ("Dasher", "Twin Swords"),
    ("Dasher", "Throwing Knives"),
    ("Dasher", "Chain & Sickle"),
    ("Dasher", "Nunchaku"),
    ("Dasher", "Staff"),
    ("Dasher", "Bow"),
    ("Dasher", "Shaman Rod"),
    ("Dasher", "Iron Fan"),
    ("Dasher", "Sword & Shield"),
    ("Dasher", "Flying Swords"),
    ("Dasher", "Curved Sword"),
    ("Dasher", "Claws"),
    ("Dasher", "Wheels"),
    ("Dasher", "Chain Whip"),
    ("Dasher", "Spinner"),
    ("Dasher", "Flute"),
    ("Dasher", "Harp"),
    ("Dasher", "Orb & Scepter"),
    ("Dasher", "Trishula"),
    ("Dasher", "Pugil Stick"),
    ("Dasher", "Lightning Sword"),
    ("Dasher", "Boomerang"),
    ("Dasher", "Sword & Hook"),
    ("Dasher", "Swallow Swords"),
    ("Dasher", "Three Sectional Staff"),
    ("Dasher", "Shadow Fan"),
    ("Dasher", "Extension Blade"),
    ("Dasher", "Dual Hookblades"),
    ("Dasher", "Wingblades"),
    ("Dasher", "Throwing Axes"),
    ("Dasher", "Wired Gloves"),
    ("Dasher", "Flame Bow"),
    ("Dasher", "Art of War Scroll"),
    ("Dasher", "Formation Wand"),
    
    ("Shadow Sprinter", "Flail"),
    ("Shadow Sprinter", "Podao"),
    ("Shadow Sprinter", "Double Pike"),
    ("Shadow Sprinter", "General's Sword"),
    ("Shadow Sprinter", "Nine Rings Blade"),
    ("Shadow Sprinter", "Double-Edge Trident"),
    ("Shadow Sprinter", "Short Rod"),
    ("Shadow Sprinter", "Javelin"),
    ("Shadow Sprinter", "Crossed Pike"),
    
    ("Diver", "Dragon Spear"),
    ("Diver", "Crescent Blade"),
    ("Diver", "Dual Blade"),
    ("Diver", "Horsehair Whip"),
    ("Diver", "Striking Sword"),
    ("Diver", "Tailsman Cards"),
    ("Diver", "Flail Sword"),
    ("Diver", "Woven Cloth");